name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    +materialized: table
    +schema: public
    +database: AVA_DB
    
    # Disable all older versions
    DataStage_To_DBT_Conversion_1:
      +enabled: false
    DataStage_To_DBT_Conversion_2:
      +enabled: false
    DataStage_To_DBT_Conversion_3:
      +enabled: false
    DataStage_To_DBT_Conversion_4:
      +enabled: false
    DataStage_To_DBT_Conversion_5:
      +enabled: true
      +materialized: table