# DBT Project Configuration for DataStage to DBT Conversion
# Project: Retail Data Mart ETL
# Source: RETAIL_DATA_MART_Job.dsx

name: 'retail_data_mart'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'retail_data_mart'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  retail_data_mart:
    # Config indicated by + and applies to all files under models/
    +materialized: table
    +schema: public
    +tags:
      - "datastage_conversion"
    
    # Specific configurations for DataStage conversion models
    DataStage_To_DBT_Conversion_1:
      +materialized: table
      +tags:
        - "datastage_conversion"
        - "retail_data_mart"
        - "version_1"
    
    DataStage_To_DBT_Conversion_2:
      +materialized: table
      +tags:
        - "datastage_conversion"
        - "retail_data_mart"
        - "version_2"
        - "production"
      +cluster_by:
        - "invoice_date"
        - "customer_id"

# Variables for job execution
vars:
  # Audit framework variables
  audit_schema: 'PUBLIC'
  
  # Job parameters (can be overridden at runtime)
  # Example: dbt run --vars '{"batch_id": "BATCH_20230525", "run_date": "2023-05-25"}'
  # batch_id: "BATCH_" || TO_CHAR(CURRENT_TIMESTAMP(), "YYYYMMDDHH24MISS")
  # run_date: CURRENT_DATE()
  commit_batch: 10000
  log_path: "/logs/dbt/retail_data_mart"
  source_connection: "AVA_DB.PUBLIC"
  target_connection: "AVA_DB.PUBLIC"

# Seeds configuration
seeds:
  retail_data_mart:
    +schema: public

# Snapshots configuration
snapshots:
  retail_data_mart:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Documentation
# on-run-start and on-run-end hooks can be used for audit logging
on-run-start:
  - "{{ log('Starting DBT run for Retail Data Mart', info=True) }}"

on-run-end:
  - "{{ log('Completed DBT run for Retail Data Mart', info=True) }}"

# Dispatch configuration for cross-database compatibility
dispatch:
  - macro_namespace: dbt
    search_order: ['retail_data_mart', 'dbt']

# Quoting configuration for Snowflake
quoting:
  database: false
  schema: false
  identifier: false