version: 2

models:
  - name: DataStage_To_DBT_Conversion_4
    description: "Customer transaction count aggregation converted from DataStage Count_Customers_Transactions_Job"
    columns:
      - name: CUSTOMERID
        description: "Customer identifier - primary grouping key from DataStage aggregator"
        data_type: integer
        tests:
          - not_null
      - name: STOCKID
        description: "Stock identifier - secondary grouping key from DataStage aggregator"
        data_type: integer
        tests:
          - not_null
      - name: TOTAL_ORDERS_NUM
        description: "Total number of transactions per customer and stock - derived from RecCount() in DataStage"
        data_type: integer
        tests:
          - not_null